#!/bin/bash

# Verifica se um número é maior que o outro

#recebe os numeros
echo "Digite o primeiro numero"
read num1
echo "Digite o segundo numero"
read num2

if [[ num1 -gt num2 ]]; then
		echo "O número $num1 é maior que $num2"
	elif [[ num2 -gt num1 ]]; then
		echo "O número $num2 é maior que $num1"
	else 
	echo "Os números são iguais."
fi